// The sequence of triangle numbers is generated by adding the natural numbers.
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
// The first ten terms would be:	1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28

// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?
// = 76576500

#include <iostream>
#include <math.h>
#define MAX 500
using namespace std;

long long triangle(long long num){
	return num * (num+1)/2;
}

bool find(long long num){
	int count = 1;
	for(int i=2; i <= sqrt(num); i++){
		if( (num % i) == 0 )
			count += 2;
		if( count >= MAX ){
			cout << num;
			return true;
		}
	}
	return false;
}

int main(){
	long long i = 0;
	while(++i){
		int tri = triangle(i);
        if(find(triangle(i)))
        	break;
	}
	return 0;
}