/*
	Each new term in the Fibonacci sequence is generated by adding 
	the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed
	four million, find the sum of the even-valued terms.
*/

#include <iostream>

int main(){
  int sum = 0;
  for(int x = 1, y = 1, z ;x<4000000; z=y, y+=x, x=z){
    sum += (x%2==0) ?x :0;
  }
  std::cout << sum;
  return 0;
}

//  LOLCode version
/*
HAI 1.2
  I HAS A W ITZ 0
  I HAS A X ITZ 1
  I HAS A Y ITZ 1
  I HAS A Z
  IM IN YR LOOP
    DIFFRINT 10 AN BIGGR OF 10 AN X
    O RLY?
      YA RLY
        GTFO
    OIC
    BOTH SAEM MOD OF X AN 2 AN 0
    O RLY?
      YA RLY
        W R SUM OF W AN W
    OIC
    Z R Y
    Y R SUM OF Y AN X
    X R Z
  IM OUTTA YR LOOP
  VISIBLE W
KTHXBYE
*/